dist: trusty
sudo: required
services:
- docker

# only build master branch (and PRs)
branches:
  only:
    - "master"

language: go
go:
- "1.14"

env:
  - GO111MODULE=on

install:
- make init
- make tools.terraform
- make dummy-edgerc

script:
- make test
- make build
- make check
- make terraform-fmt
- make terraform-lint
